# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# random change

language: R
sudo: false
cache: packages

r_packages:
  - covr
  - devtools

after_success:
  - Rscript -e 'library(covr); codecov()'

# safelist
branches:
  only:
  - master
  - development